spring:
  application:
    name: 223spring_boot_loan_task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update

carproperties:
  maxCar: 6
  listOfDisabledSort:
    - model
    - id

loan:
  minimalIncome: 40000
  minimalCarCost: 1000000
  percentOfLoanByCarCost: 0.3
