spring:
  application:
    name: 222spring_boot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

carproperties:
  maxCar: 6
  listOfDisabledSort:
    - model
    - id

